# Generated by Django 4.1.1 on 2022-10-07 17:45

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dgram', '0003_alter_postimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'date_posted'], unique=True),
        ),
    ]
