# Generated by Django 4.1.1 on 2022-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/avatars/default.jpg', upload_to='profiles/avatars'),
        ),
    ]
